name: Deploy Rubrica-DW-3 to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      # Paso 1: Obtener el código
      - uses: actions/checkout@v4
      
      # Paso 2: Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Versión LTS más reciente
          cache: 'npm'
      
      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: npm ci
      
      # Paso 4: Construir el proyecto (ajusta según tu proyecto)
      - name: Build project
        run: npm run build
      
      # Paso 5: Desplegar
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true  # Mantiene solo los últimos archivos desplegados
